import { AuthProvider } from "./providers";
import "./globals.css";
import { Inter } from "next/font/google";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css'; // Import CSS for react-toastify

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Voosh Todo-App",
  description: "Generated by dhanaraja",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
          <ToastContainer />
        </AuthProvider>
      </body>
    </html>
  );
}
